#ifndef BOOTLOADER_PROTOCOL_H
#define BOOTLOADER_PROTOCOL_H

#include "data_structures/span.h"

#include <pybind11/pybind11.h>

namespace py = pybind11;

namespace Bootloader {

/*  Bootloader Protocol Use Cases:

General:
- Read bootloader version
- Read application version && validity check
- Read hardware information


Application:
- Download app into internal MCU flash
- Download app into external flash (FPGA)
- Download app into SRAM (MCU or FPGA)
- Boot app from internal MCU flash
- Boot app from external flash (FPGA)
  (running in SRAM)


Bootloader Upgrade:
- TBD


Data File
- Upload data file to host computer (any memory region)

*/


/*  Steps to downloading an image:
     1. Detect compatible hardware / bootloader
     2. Check app version / validity to see if it needs updating
     3. (Flash) Erase target flash sector(s)
     4. Configure transfer: start_address, size_bytes
     5. Transfer all segments (with ACK/retry?)
     6. Verify image

    Questions:
     - Is segment size fixed per PHY type?

*/

/******************************************************************************
 *  Enums
 ******************************************************************************/

 enum class ImageStatus : uint8_t {
    kUnknown = 0,
    kNotSupported = 1,
    kInvalid = 2,
    kErased = 3,
    kBusy = 4,
    kValid = 5,
    kNumImageStatus = 6
 };

 enum class TransferType : uint8_t {
    kUnknown = 0,
    kFlashWrite = 1,
    kFlashRead = 2,
    kSramWrite = 3,
    kSramRead = 4,
    kNumTransferTypes = 5
 };

 enum class MessageType : uint8_t {
    kUnknown = 0,

    // Response messages
    kCommandAccept,     // value8 = command type
    kCommandReject,     // value8 = command type, value32 = error code
    kSegmentAck,        // value32 = segment number
    kSegmentNak,        // value32 = segment number
    kTransferSuccess,
    kTransferFailed,    // value32 = error code

    // Bidirectional, discrete jobs
    kBootloaderInfo1,
    kImageStatus1,
    kBoardVersion1,
    kAppVersion1,

    // Client -> Bootloader, tracked as one job
    kSetStartAddress,    // value32 = start address
    kSetSizeBytes,       // value32 = size bytes
    kDoErase,            // TODO: implement this
    kStartTransfer,      // TODO: value8 = transfer type (Don't care for now)
    kMemTransferSegment,
    kFinalizeTransfer,
    kReset,

    kNumMessageTypes
};


/******************************************************************************
 *  Information Message Types
 ******************************************************************************/

struct BootloaderInfo1 {
    static constexpr uint8_t kMagic = 0xB1;
    uint8_t magic; // Must match kMagic
    uint8_t protocol_version; // Valid range = [1, 255]
    uint8_t bootloader_major; // Valid range = [1, 255]
    uint8_t bootloader_minor; // Valid range = [0, 255]
};

static_assert(sizeof(BootloaderInfo1) == 4U, "BootloaderInfo1 size is incorrect");

struct ImageStatus1 {
    uint8_t status_a;  // ImageStatus enum
    uint8_t status_b;  // ImageStatus enum
    uint8_t reserved[2];
};

static_assert(sizeof(ImageStatus1) == 4U, "ImageStatus1 size is incorrect");

struct BoardVersion1 {
    uint16_t board_type;          // Valid range = [1, 65535]
    uint8_t  board_version_major; // Valid range = [1, 255]
    uint8_t  board_version_minor; // Valid range = [0, 255]
};

static_assert(sizeof(BoardVersion1) == 4U, "BoardVersion1 size is incorrect");

struct AppVersion1 {
    uint8_t  app_version_major; // Valid range = [1, 255]
    uint8_t  app_version_minor; // Valid range = [0, 255]
    uint8_t  reserved[2];
};

static_assert(sizeof(AppVersion1) == 4U, "AppVersion1 size is incorrect");


/******************************************************************************
 *  Packet Types
 ******************************************************************************/

/*
 * Job IDs are generated by the client, and echoed by the bootloader. Multi-step
 * operations like sector erase or image transfer are tracked as one job. Simple
 * operations like reading a version count as one job. The job ID is incremented
 * for each job.
 */
struct Message {
    static constexpr uint8_t kInvalidJobId = UINT8_MAX;
    uint8_t  message_type;
    uint8_t  job_id;
    uint8_t  reserved;
    uint8_t  value8;    // TODO: use this as CRC-8?
    uint32_t value32;
};

static_assert(sizeof(Message) == 8U, "Message size is incorrect");

// No CRC: it is assumed this fits in 1 packet and the link layer provides a CRC.
// The full image is verified after transfer is complete.
template<size_t kSegmentSizeBytes>
struct MemTransferSegment {
    uint8_t  message_type;
    uint8_t  job_id;
    uint16_t segment_number; // Allowed to wrap around
    uint8_t  memory[kSegmentSizeBytes];
};

using MemTransferSegmentCan = MemTransferSegment<4U>;
using MemTransferSegmentHdlc = MemTransferSegment<64U>;
using MemTransferSegmentEthernet = MemTransferSegment<1024U>;


struct MemTransferSegmentGeneric {
    uint8_t  message_type;
    uint8_t  job_id;
    uint16_t segment_number; // Allowed to wrap around
    Span<uint8_t> data;
};


/******************************************************************************
 *  Python Bindings
 ******************************************************************************/

py::enum_<ImageStatus>(m, "ImageStatus")
.value("kUnknown", ImageStatus::kUnknown)
.value("kNotSupported", ImageStatus::kNotSupported)
.value("kInvalid", ImageStatus::kInvalid)
.value("kErased", ImageStatus::kErased)
.value("kBusy", ImageStatus::kBusy)
.value("kValid", ImageStatus::kValid)
.export_values();

py::enum_<TransferType>(m, "TransferType")
.value("kUnknown", TransferType::kUnknown)
.value("kFlashWrite", TransferType::kFlashWrite)
.value("kFlashRead", TransferType::kFlashRead)
.value("kSramWrite", TransferType::kSramWrite)
.value("kSramRead", TransferType::kSramRead)
.export_values();

py::enum_<MessageType>(m, "MessageType")
.value("kUnknown", MessageType::kUnknown)
.value("kCommandAccept", MessageType::kCommandAccept)
.value("kCommandReject", MessageType::kCommandReject)
.value("kSegmentAck", MessageType::kSegmentAck)
.value("kSegmentNak", MessageType::kSegmentNak)
.value("kTransferSuccess", MessageType::kTransferSuccess)
.value("kTransferFailed", MessageType::kTransferFailed)
.value("kBootloaderInfo1", MessageType::kBootloaderInfo1)
.value("kImageStatus1", MessageType::kImageStatus1)
.value("kBoardVersion1", MessageType::kBoardVersion1)
.value("kAppVersion1", MessageType::kAppVersion1)
.value("kSetStartAddress", MessageType::kSetStartAddress)
.value("kSetSizeBytes", MessageType::kSetSizeBytes)
.value("kDoErase", MessageType::kDoErase)
.value("kStartTransfer", MessageType::kStartTransfer)
.value("kMemTransferSegment", MessageType::kMemTransferSegment)
.value("kFinalizeTransfer", MessageType::kFinalizeTransfer)
.value("kReset", MessageType::kReset)
.export_values();

py::class_<BootloaderInfo1>(m, "BootloaderInfo1")
.def(py::init<>())
.def(py::init<uint8_t, uint8_t, uint8_t>())
.def_readwrite("magic", &BootloaderInfo1::magic)
.def_readwrite("protocol_version", &BootloaderInfo1::protocol_version)
.def_readwrite("bootloader_major", &BootloaderInfo1::bootloader_major)
.def_readwrite("bootloader_minor", &BootloaderInfo1::bootloader_minor)
.def_readonly_static("kMagic", &BootloaderInfo1::kMagic);

py::class_<ImageStatus1>(m, "ImageStatus1")
.def(py::init<>())
.def(py::init<uint8_t, uint8_t>())
.def_readwrite("status_a", &ImageStatus1::status_a)
.def_readwrite("status_b", &ImageStatus1::status_b)

py::class_<BoardVersion1>(m, "BoardVersion1")
.def(py::init<>())
.def(py::init<uint16_t, uint8_t, uint8_t>())
.def_readwrite("board_type", &BoardVersion1::board_type)
.def_readwrite("board_version_major", &BoardVersion1::board_version_major)
.def_readwrite("board_version_minor", &BoardVersion1::board_version_minor)

py::class_<AppVersion1>(m, "AppVersion1")
.def(py::init<>())
.def(py::init<uint8_t, uint8_t>())
.def_readwrite("app_version_major", &AppVersion1::app_version_major)
.def_readwrite("app_version_minor", &AppVersion1::app_version_minor)
.def_readonly_static("kMagic", &AppVersion1::kMagic);


#endif // BOOTLOADER_PROTOCOL_H