#pragma once

#include <stdint.h>
#include <climits>

#include "data_structures/span.h"

namespace Bootloader {

/******************************************************************************
 *  Enums
 ******************************************************************************/

 enum class ImageStatus : uint8_t {
    kUnknown = 0,
    kNotSupported = 1,
    kInvalid = 2,
    kErased = 3,
    kBusy = 4,
    kValid = 5,
    kNumImageStatus = 6
 };

 enum class TransferType : uint8_t {
    kUnknown = 0,
    kFlashWrite = 1,
    kFlashRead = 2,
    kSramWrite = 3,
    kSramRead = 4,
    kNumTransferTypes = 5
 };

 enum class MessageType : uint8_t {
    kUnknown = 0,

    // Response messages
    kCommandAccept,     // value8 = command type
    kCommandReject,     // value8 = command type, value32 = error code
    kSegmentAck,        // value32 = segment number
    kSegmentNak,        // value32 = segment number
    kTransferSuccess,
    kTransferFailed,    // value32 = error code

    // Bidirectional, discrete jobs
    kBootloaderInfo1,
    kImageStatus1,
    kBoardVersion1,
    kAppVersion1,

    // Client -> Bootloader, tracked as one job
    kSetStartAddress,    // value32 = start address
    kSetSizeBytes,       // value32 = size bytes
    kDoErase,            // TODO: implement this
    kStartTransfer,      // TODO: value8 = transfer type (Don't care for now)
    kMemTransferSegment,
    kFinalizeTransfer,
    kReset,

    kNumMessageTypes
};

inline bool isValidMessageType(MessageType message_type) noexcept {
    static_assert(static_cast<uint8_t>(MessageType::kUnknown) == 0U, "MessageType::kUnknown must be 0");
    return (message_type != MessageType::kUnknown) && (message_type < MessageType::kNumMessageTypes);
}

/******************************************************************************
 *  Information Message Types
 ******************************************************************************/

struct BootloaderInfo1 {
    static constexpr uint8_t kMagic = 0xB1;
    uint8_t magic; // Must match kMagic
    uint8_t protocol_version; // Valid range = [1, 255]
    uint8_t bootloader_major; // Valid range = [1, 255]
    uint8_t bootloader_minor; // Valid range = [0, 255]
};

static_assert(sizeof(BootloaderInfo1) == 4U, "BootloaderInfo1 size is incorrect");

struct ImageStatus1 {
    uint8_t status_a;  // ImageStatus enum
    uint8_t status_b;  // ImageStatus enum
    uint8_t reserved[2];
};

static_assert(sizeof(ImageStatus1) == 4U, "ImageStatus1 size is incorrect");

struct BoardVersion1 {
    uint16_t board_type;          // Valid range = [1, 65535]
    uint8_t  board_version_major; // Valid range = [1, 255]
    uint8_t  board_version_minor; // Valid range = [0, 255]
};

static_assert(sizeof(BoardVersion1) == 4U, "BoardVersion1 size is incorrect");

struct AppVersion1 {
    uint8_t  app_version_major; // Valid range = [1, 255]
    uint8_t  app_version_minor; // Valid range = [0, 255]
    uint8_t  reserved[2];
};

static_assert(sizeof(AppVersion1) == 4U, "AppVersion1 size is incorrect");


/******************************************************************************
 *  Packet Types
 ******************************************************************************/

/*
 * Job IDs are generated by the client, and echoed by the bootloader. Multi-step
 * operations like sector erase or image transfer are tracked as one job. Simple
 * operations like reading a version count as one job. The job ID is incremented
 * for each job.
 */
struct Message {
    static constexpr uint8_t kInvalidJobId = UINT8_MAX;
    uint8_t  message_type;
    uint8_t  job_id;
    uint8_t  reserved;
    uint8_t  value8;    // TODO: use this as CRC-8?
    uint32_t value32;
};

static_assert(sizeof(Message) == 8U, "Message size is incorrect");

// No CRC: it is assumed this fits in 1 packet and the link layer provides a CRC.
// The full image is verified after transfer is complete.
template<size_t kSegmentSizeBytes>
struct MemTransferSegment {
    uint8_t  message_type;
    uint8_t  job_id;
    uint16_t segment_number; // Allowed to wrap around
    uint8_t  memory[kSegmentSizeBytes];
};


/******************************************************************************
 *  Packet Helpers
 ******************************************************************************/

// Arbitrary segment size so the bootloader is independent of segment size template argument
// This is for bootloader internal use only, NOT a packet sent on the wire.
struct MemTransferSegmentView {
    uint8_t  message_type;
    uint8_t  job_id;
    uint16_t segment_number; // Allowed to wrap around
    Span<const uint8_t> data;
};

} // namespace Bootloader
